### ISSUE TITLE
Update project to work with latest UWP version

### ISSUE THREAD

**Issue by ngducnghia** [davidezordan/playready_livedash_UWP#1]
Hi David,

Firstly, I'm very appreciated your works here, it helps solved my problem today. However I had to make few changes so it can works with Anniversary UWP update. I want to contribute my changes so everyone can use this sample. Lets me know if that is fine for you.

**Comment by davidezordan** [comment]
Sure! Just open a PR and I will approve it.

**Comment by ngducnghia** [comment]
PR opened

**Comment by davidezordan** [comment]
Approved, thanks for the PR!
